<a href="https://colab.research.google.com/github/SimenKlemp/.github/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem 1**

In [3]:
import tensorflow as tf
import keras as ks

print(tf.__version__)
print(ks.__version__)

2.9.2
2.9.0


# **Problem 2**

In [36]:

x= tf.constant([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])
y = tf.constant([34, 28, 45, 67, 89, 93, 24, 49, 11, 7])

z = tf.add(x,y)

print(z)


tf.Tensor([134 129 147 170 193 198 130 156 119 116], shape=(10,), dtype=int32)


# **Problem 3**

In [5]:
x1 = tf.constant([[1,2,3,4],[5,6,7,8]])

x2 = tf.stack([x1, x1, x1, x1])

print(x2)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(4, 2, 4), dtype=int32)


# **Problem 4**

In [6]:
x1 = tf.constant([[1,2,3,4],[5,6,7,8]])

x2= tf.stack([x1])

print(x2)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]], shape=(1, 2, 4), dtype=int32)


# **Problem 5**

In [7]:
x1 = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

x2 = tf.reshape(x1, [6,2])

print(x2)



tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)


# **Problem 6**


In [9]:
a = tf.constant([1.12])
b = tf.constant([2.34])
c = tf.constant([0.72])
d = tf.constant([0.81])
f = tf.constant([19.83])

x = 1 + a/b + c/f**2

s = (b - a)/(d - c)

r = (1/((1/a) + (1/b) + (1/c) + (1/d)))

y = a*b*(1/c)*((f**2)/2)


print(x)
print(s)
print(r)
print(y)

tf.Tensor([1.4804634], shape=(1,), dtype=float32)
tf.Tensor([13.555558], shape=(1,), dtype=float32)
tf.Tensor([0.25357127], shape=(1,), dtype=float32)
tf.Tensor([715.6765], shape=(1,), dtype=float32)


# **Problem 7**





In [10]:
##Defining the matrixes

A = tf.constant([[4,-2,1],
                 [6,8,-5],
                 [7,9,10]])

B = tf.constant([[6,9,-4],
                 [7,5,3],
                 [-8,2,1]])

C = tf.constant([[-4,-5,2],
                 [10,6,1],
                 [3,-9,8]])

### **a. Associative property** **--> A(B+C) = AB + AC**



In [33]:
##Defining the matrix equations
mat_add = tf.add(B, C)
mat_mul_left = tf.matmul(A, mat_add)
mat_mul_right = tf.matmul(A,B) + tf.matmul(A,C)

print(mat_mul_left)
print("------------")
print(mat_mul_right)
print("-----------")

##Check equality of both sides
tf.math.equal(mat_mul_left, mat_mul_right)
 


tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)
------------
tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)
-----------


<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### **b. Distributive property** **--> (AB)C = A(BC) **

In [34]:
##Defining the matrix equations
mat_mul_left = tf.matmul(tf.matmul(A, B), C)
mat_mul_right = tf.matmul(A, tf.matmul(B,C))

print(mat_mul_left)
print("------------")
print(mat_mul_right)
print("-----------")

##Check equality of both sides
tf.math.equal(mat_mul_left, mat_mul_right)


tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)
------------
tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)
-----------


<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>