<a href="https://colab.research.google.com/github/SimenKlemp/Tensorflow/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [32]:
import tensorflow as tf
import keras as ks

x1 = tf.constant([0.1])
x2 = tf.constant([0.2])
w1 = tf.constant([0.15])
w2 = tf.constant([0.05])
b1 = tf.constant([0.33])
z1 = tf.constant([0.355])
w3 = tf.constant([0.36])
b2 = tf.constant([0.56])

@tf.function
def z2(x):
  return ((x*w3) + b2)

@tf.function
def linear(x):
  return x

@tf.function
def sigmoid(x):
  return (1/(1+tf.math.exp(-x)))

@tf.function
def null():
  return 0

@tf.function
def tanh(x):
  return ((tf.math.exp(x) - tf.math.exp(-x))/(tf.math.exp(x) + tf.math.exp(-x)))


@tf.function
def ReLu(x):
  if x < 0:
    return 0.
  return x



#Linear
a1_linear = linear(z1)
z2_linear = z2(a1_linear)
a2_linear = linear(z2_linear)

#Tanh
a1_tanh = tanh(z1)
z2_tanh = z2(a1_tanh)
a2_tanh = tanh(z2_tanh)

#ReLu
a1_reLu = ReLu(z1)
z2_reLu = z2(a1_reLu)
a2_reLu = linear(z2_reLu)


print("Linear")
print(a1_linear)
print(a2_linear)
print("\n")

print("Tanh")
print(a1_tanh)
print(a2_tanh)
print("\n")

print("reLU")
print(a1_reLu)
print(a2_reLu)




Linear
tf.Tensor([0.355], shape=(1,), dtype=float32)
tf.Tensor([0.6878], shape=(1,), dtype=float32)


Tanh
tf.Tensor([0.34080228], shape=(1,), dtype=float32)
tf.Tensor([0.5932646], shape=(1,), dtype=float32)


reLU
tf.Tensor([0.355], shape=(1,), dtype=float32)
tf.Tensor([0.6878], shape=(1,), dtype=float32)


Problem 2

In [42]:
x1 = tf.constant([-4.0])
x2 = tf.constant([0.5])
x3 = tf.constant([4.0])

def sigmoid_derivate(x):
  return (sigmoid(x)*(1-sigmoid(x)))

def tanH_derivate(x):
  return (1 - tanh(x)**2)

def reLu_derivate(x):
  if(x <= 0):
    return tf.constant([0])
  return tf.constant([1])

#gradient for sigmoid
gradient_sigmoid_x1 = sigmoid_derivate(x1)
gradient_sigmoid_x2 = sigmoid_derivate(x2)
gradient_sigmoid_x3 = sigmoid_derivate(x3)

#gradient for tanh
gradient_tanH_x1 = tanH_derivate(x1)
gradient_tanH_x2 = tanH_derivate(x2)
gradient_tanH_x3 = tanH_derivate(x3)

#gradient for reLu
gradient_reLu_x1 = reLu_derivate(x1)
gradient_reLu_x2 = reLu_derivate(x2)
gradient_reLu_x3 = reLu_derivate(x3)


print("Gradient for sigmoid:")
print(gradient_sigmoid_x1)
print(gradient_sigmoid_x2)
print(gradient_sigmoid_x3)
print("\n")


print("Gradient for tanh:")
print(gradient_tanH_x1)
print(gradient_tanH_x2)
print(gradient_tanH_x3)
print("\n")

print("Gradient for reLu:")
print(gradient_reLu_x1)
print(gradient_reLu_x2)
print(gradient_reLu_x3)



Gradient for sigmoid:
tf.Tensor([0.01766271], shape=(1,), dtype=float32)
tf.Tensor([0.23500371], shape=(1,), dtype=float32)
tf.Tensor([0.01766273], shape=(1,), dtype=float32)


Gradient for tanh:
tf.Tensor([0.00134087], shape=(1,), dtype=float32)
tf.Tensor([0.78644776], shape=(1,), dtype=float32)
tf.Tensor([0.00134087], shape=(1,), dtype=float32)


Gradient for reLu:
tf.Tensor([0], shape=(1,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)


Problem 3

In [47]:
V1 = tf.constant([2.3, 1.2, 0.3, 0.0])
V2 = tf.constant([1.9, 1.7, 2.6, 0.2, 1.3])

soft_max_1 = tf.nn.softmax(V1)
soft_max_2 = tf.nn.softmax(V2)

print("Soft max V1:")
print(soft_max_1)
print("\n")
print("Soft max V2:")
print(soft_max_2)



Soft max V1:
tf.Tensor([0.6375659  0.21222727 0.08628516 0.06392162], shape=(4,), dtype=float32)


Soft max V2:
tf.Tensor([0.21910708 0.17938972 0.44122744 0.04002725 0.12024851], shape=(5,), dtype=float32)


Problem 4

In [49]:
def cost_function(target, compValue):
  return -1*((target * tf.math.log(compValue) + (1 - target) * (tf.math.log(1 - compValue))))
  

cf1 = cost_function(0, 0.95)
cf2 = cost_function(0, 0.8)
cf3 = cost_function(0, 0.6)
cf4 = cost_function(0, 0.4)
cf5 = cost_function(0, 0.1)

cf6 = cost_function(1, 0.95)
cf7 = cost_function(1, 0.8)
cf8 = cost_function(1, 0.6)
cf9 = cost_function(1, 0.4)
cf10 = cost_function(1, 0.1)

print("Target = 0")
print(cf1)
print(cf2)
print(cf3)
print(cf4)
print(cf5)
print("\n")

print("Target = 1")
print(cf6)
print(cf7)
print(cf8)
print(cf9)
print(cf10)








Target = 0
tf.Tensor(2.9957323, shape=(), dtype=float32)
tf.Tensor(1.609438, shape=(), dtype=float32)
tf.Tensor(0.9162907, shape=(), dtype=float32)
tf.Tensor(0.5108256, shape=(), dtype=float32)
tf.Tensor(0.105360545, shape=(), dtype=float32)


Target = 1
tf.Tensor(0.051293306, shape=(), dtype=float32)
tf.Tensor(0.22314353, shape=(), dtype=float32)
tf.Tensor(0.5108256, shape=(), dtype=float32)
tf.Tensor(0.9162907, shape=(), dtype=float32)
tf.Tensor(2.3025851, shape=(), dtype=float32)


Problem 5

In [51]:
a = tf.constant([[5, 2, 3], [26, 56, 92], [3, 0, 26]])

#argmax on column 0 and 1
a1 = tf.argmax(a,axis=0)
a2 = tf.argmax(a,axis=1)

print("a1:")
print(a1)
print("\n")
print("a2:")
print(a2)



a1:
tf.Tensor([1 1 1], shape=(3,), dtype=int64)


a2:
tf.Tensor([0 2 2], shape=(3,), dtype=int64)


Problem 6

In [52]:
W1 = tf.constant([[-4.], [-6.], [-5.], [3.], [6.], [4.]])
b1 = tf.constant([[-2.], [3.], [-2.]])
W2 = tf.constant([[5.], [-9.], [7.]])
b2 = tf.constant([4.])

def sigmoid(x):
  return (1/(1+tf.math.exp(-x)))

def error(computed_value, true_output):
  return (computed_value - true_output)**2

@tf.function
def computed_value(x1, x2):
  z11 = (x1 * W1[0]) + (x2 * W1[3]) + b1[0]
  z12 = (x1 * W1[1]) + (x2 * W1[4]) + b1[1]
  z13 = (x1 * W1[2]) + (x2 * W1[5]) + b1[2]

  a1 = sigmoid(z11)
  a2 = sigmoid(z12)
  a3 = sigmoid(z13)

  z21 = ((a1 * W2[0]) + (a2 * W2[1]) +  (a3 * W2[2]) + (b2[0]))

  a_out = sigmoid(z21)

  return a_out


computet_output_1 = computed_value(0.,0.)
computet_output_2 = computed_value(1,0)
computet_output_3 = computed_value(0,1)
computet_output_4 = computed_value(1,1)

error_output_1 = error(computet_output_1, 0)
error_output_2 = error(computet_output_2, 1)
error_output_3 = error(computet_output_3, 1)
error_output_4 = error(computet_output_4, 0)



print("Computed output and error:")
print("Input 1: 0, Input 2: 0")
print(computet_output_1)
print(error_output_1)
print("\n")
print("Input 1: 1, Input 2: 0")
print(computet_output_2)
print(error_output_2)
print("\n")
print("Input 1: 0, Input 2: 1")
print(computet_output_3)
print(error_output_3)
print("\n")
print("Input 1: 1, Input 2: 1")
print(computet_output_4)
print(error_output_4)















  






Computed output and error:
Input 1: 0, Input 2: 0
tf.Tensor([0.04137863], shape=(1,), dtype=float32)
tf.Tensor([0.00171219], shape=(1,), dtype=float32)


Input 1: 1, Input 2: 0
tf.Tensor([0.97319275], shape=(1,), dtype=float32)
tf.Tensor([0.00071863], shape=(1,), dtype=float32)


Input 1: 0, Input 2: 1
tf.Tensor([0.9920135], shape=(1,), dtype=float32)
tf.Tensor([6.3783955e-05], shape=(1,), dtype=float32)


Input 1: 1, Input 2: 1
tf.Tensor([0.01791469], shape=(1,), dtype=float32)
tf.Tensor([0.00032094], shape=(1,), dtype=float32)
